const TRACK_TEXTURE_SLICES = {
  laneSurfaceTop: 0,
  laneSurfaceBottom: 0.74,
  lowerApronTop: 0.69,
};

const COMMON_SCENE = {
  skyRatio: 0.4,
  skyRatioMobile: 0.32,
  botRatio: 0.16,
  botRatioMobile: 0.05,
  minBottomPad: 120,
  minBottomPadMobile: 72,
  visualLaneCount: 6,
  laneSlotMode: 'top',
  racerYOffset: 0,
};

function makeScene(config) {
  const {
    key,
    name,
    pickerLabel,
    sky,
    folder,
    ground,
    groundDark,
    track,
    laneLine,
    trackTextureSlices,
    ...optionalFields
  } = config;
  return {
    key: key,
    name: name,
    pickerLabel: pickerLabel,
    sky: sky,
    ...COMMON_SCENE,
    ...optionalFields,
    backdrop: '/background/' + folder + '/01-background.png',
    trackTexture: '/background/' + folder + '/02-track.png',
    trackTextureSlices: { ...TRACK_TEXTURE_SLICES, ...(trackTextureSlices || {}) },
    ground: ground,
    groundDark: groundDark,
    track: track,
    laneLine: laneLine,
  };
}

const SCENES = [
  makeScene({
    key: 'sky-kingdom',
    name: 'Sky Kingdom',
    pickerLabel: 'Sky',
    folder: '08-sky-kingdom',
    sky: ['#4f7c69', '#c9f1c8'],
    ground: '#5d9827',
    groundDark: '#3d6f19',
    track: '#cf523d',
    laneLine: '#fff7ee',
  }),
  makeScene({
    key: 'mountain',
    name: 'Mountain',
    pickerLabel: 'Mountain',
    folder: '01-mountain-valley',
    sky: ['#4c95db', '#b9e3ff'],
    ground: '#5f9034',
    groundDark: '#436723',
    track: '#345f9d',
    laneLine: '#eff6ff',
  }),
  makeScene({
    key: 'ancient-greek',
    name: 'Ancient Greek',
    pickerLabel: 'Greek',
    folder: '03-ancient-greek',
    sky: ['#89c5e0', '#f7f0d9'],
    ground: '#98a45f',
    groundDark: '#6c7640',
    track: '#c17b4b',
    laneLine: '#fff4db',
  }),
  makeScene({
    key: 'desert-grand-prix',
    name: 'Desert Grand Prix',
    pickerLabel: 'Desert',
    folder: '04-desert-grand-prix',
    sky: ['#f7bf6c', '#ffe6ad'],
    ground: '#c7a15a',
    groundDark: '#8f6a34',
    track: '#cf8050',
    laneLine: '#fff0d7',
  }),
  makeScene({
    key: 'neo-tokyo',
    name: 'Neo Tokyo',
    pickerLabel: 'Tokyo',
    folder: '02-neo-tokyo',
    sky: ['#35569a', '#c2cbff'],
    ground: '#43627b',
    groundDark: '#243446',
    track: '#5979b8',
    laneLine: '#eef4ff',
  }),
  makeScene({
    key: 'space-colony',
    name: 'Space Colony',
    pickerLabel: 'Space',
    folder: '06-space-colony',
    sky: ['#19284c', '#6e8fc0'],
    ground: '#57677b',
    groundDark: '#303846',
    track: '#7b889d',
    laneLine: '#f5fbff',
  }),
  makeScene({
    key: 'tropical-island',
    name: 'Tropical Island',
    pickerLabel: 'Island',
    folder: '05-tropical-island',
    sky: ['#4eb8ed', '#cff8ff'],
    ground: '#4ba35a',
    groundDark: '#2d6d39',
    track: '#d46843',
    laneLine: '#fff8ea',
    hideRuntimeStartLine: true,
    finishLineInsetTopScale: 0.4,
    finishLineInsetBottomScale: 0.4,
    skyRatioMobile: 0.31,
    botRatioMobile: 0,
    minBottomPadMobile: 0,
    trackHeightScaleMobile: 0.78,
    trackTextureRenderMode: 'proportional',
    trackTextureSlices: {
      laneSurfaceTop: 0.225,
      laneSurfaceBottom: 0.8,
      lowerApronTop: 0.8,
    },
  }),
  makeScene({
    key: 'volcanic-racing',
    name: 'Volcanic Racing',
    pickerLabel: 'Volcano',
    folder: '07-volcanic-racing',
    sky: ['#5f2d26', '#f2995a'],
    ground: '#594239',
    groundDark: '#31211d',
    track: '#8b4334',
    laneLine: '#ffe6c8',
  }),
];
export { SCENES };
